### PR TITLE
Configurable colours

### PR DESCRIPTION
**Pull request by michaeldfallen**
This pull request provides the ability to modify the colours used for the various parts of the prompt. It was requested in issue #12. It provides the option of using either ENV vars or an rc file at `~/.gitradarrc`.

The only thing missing at the moment is documentation but it's 1am here so I'll do it in the morning.

@apas, @jackmaney, @jedsmith, @Droogans: code review?

### CODE REVIEW

**Comment by jackmaney** [comment]
I have over four hours of meetings today (send help!), so I don't think I'll get to a code review today, but I'll look it over when I can. Thank you for your work on this.

**Comment by Droogans** [comment]
Looks like a good starting point, but can you include the branch name as configurable too? All the other colors render fine on a default instance of "terminal" (Pro theme) for Yosemite, except that the branch name is as black as the background.

I'm not sure why the demo shows that the branch names are grey in the README. I'd really like to make them white.

**Comment by michaeldfallen** [comment]
@Droogans I did change them to the default color, which would be white, in https://github.com/michaeldfallen/git-radar/commit/670471cbbee32e461773e8f549f7770a5949a078. I just haven't got around to taking fresh screenshots (they take a while).

You're right, the branch name should also be configurable. I'll add that in.

**Comment by michaeldfallen** [comment]
Ok, that last commit adds the ability to configure the colour of the branch reference and the symbol used to represent master (which I set as default as an italic m, just cause I like it :trollface:). Time for documentation and then I'll merge.

**Comment by Droogans** [comment]
Excellent!

The only enhancement I can think of that works with the system you're building is to (later, of course) expose some generic themes. A light and a dark theme that work well for folks who are using a typical white on black/black on white theme. I imagine most are.

That way you can skip the configuration file entirely and swap it out with a command line arg.

``` sh
export PS1="$PS1\$(git-radar --bash --theme=dark )"
```

**Comment by apas** [comment]
Hey -- didn't have time to do any code review but browsed around some of the updated files. I'll take @Droogans word it's ok! :grin: :+1:

**Comment by michaeldfallen** [comment]
Cool, I'll write some docs today and merge it.

**Pull request merged**
