### PR TITLE
Prompt format string

### PR DESCRIPTION
**Pull request by michaeldfallen**
In response issues #62, #57, #54, #17 (so quite a lot of people) and pull request #40, which was an attempt to address some of these points, I have added the ability to describe the shape of the prompt fully through a format string.

You export this as `GIT_RADAR_FORMAT` or set it in your `.gitradarrc` file.

`%{remote}` - Output the remote status part
`%{branch}` - Output the branch name, or sha reference if detached
`%{local}` - Output the local commit diff
`%{changes}` - Output the file changes

With this you can create very flexible and unique prompt, for example:

`${branch}%{local}%{changes}` = `master1↑1M`
`[${branch}] - %{local} - %{changes}` = `[master] - 1↑ - 1M`

It also supports prefixes and suffixes that only output if there is something to output:

`%{[prefix] :local: [suffix]}` with no local commits would produce nothing

with local commits would produce `[prefix] 1↑ [suffix]`

It also supports both zsh colours and bash colour codes so you can colour the parts you add to the prompt really easily.

### CODE REVIEW

**Comment by michaeldfallen** [comment]
I haven't done any documentation yet but the basic functionality is working. I've also switched the basic prompt in prompt.zsh and prompt.bash to use the new render_prompt function and a default `GIT_RADAR_FORMAT` setting that mimics the original prompt shape.

**Comment by n10v** [comment]
Wow
Good idea
👍

**Comment by reicolina** [comment]
:+1:  It looks good @michaeldfallen ! Thanks for taking the time to address these. :muscle:

**Comment by mcphailtom** [comment]
Looks great

**Comment by michaeldfallen** [comment]
Thanks guys. I want to run a few performance tests to make sure the extra subshells and sed command don't slow down too much.

**Comment by slackorama** [comment]
This fails for me on Ubuntu:

```
render_prompt:12: failed to compile regex: Invalid content of \{\}                                                                                                                             
render_prompt:20: failed to compile regex: Invalid content of \{\}
render_prompt:28: failed to compile regex: Invalid content of \{\}
render_prompt:36: failed to compile regex: Invalid content of \{\}
```

This fixes it:

```
diff --git a/radar-base.sh b/radar-base.sh
index d5456d0..464ac45 100755
--- a/radar-base.sh
+++ b/radar-base.sh
@@ -494,8 +494,8 @@ render_prompt() {
   local_sed=""
   changes_sed=""

-  if_pre="%{([^%{}]{1,}:){0,1}"
-  if_post="(:[^%{}]{1,}){0,1}}"
+  if_pre="%\{([^%{}]{1,}:){0,1}"
+  if_post="(:[^%{}]{1,}){0,1}\}"
   sed_pre="%{\(\([^%^{^}]*\)\:\)\{0,1\}"
   sed_post="\(\:\([^%^{^}]*\)\)\{0,1\}}"
```

**Comment by n10v** [comment]
And when will be git-radar update with this feature?

**Comment by michaeldfallen** [comment]
@bogem sorry, I've been away on honeymoon and my new wife wouldn't much like it if I spent the time coding. Back now and I'm going to look in to this and merge soon. Just looking in to the performance and the bug @slackorama mentioned above.

**Comment by slackorama** [comment]
Congrats on the marriage! Tell your wife I said thanks for git-radar. It's a huge time saver.

I found another issue in this branch. If your branch has a slash in it (if you use git-flow branches are named "feature/some_cool_fix"), it will break the sed commands:

This works as a fix for me:

```
@@ -508,7 +508,7 @@ render_prompt() {
     fi
   fi
   if [[ $PROMPT_FORMAT =~ ${if_pre}branch${if_post} ]]; then
-    branch_result="$(readable_branch_name)"
+    branch_result="$(readable_branch_name | sed -e 's/\//\\\//')"
     if [[ -n "$branch_result" ]]; then
       branch_sed="s/${sed_pre}branch${sed_post}/\2${branch_result}\4/"
     else
```

Let me know if you want me to put together a PR or not.

**Comment by michaeldfallen** [comment]
@slackorama thanks :-) and good catch. This was a major change so thanks for flushing out the bugs. I've created performance tests in master and run them on this, doesn't seem to slow down much, 10ms at most. The real slow down is `git status --porcelain` which I think I need to async at some point but that's out of scope for this.

**Comment by michaeldfallen** [comment]
I've added the fixes by @slackorama so I think this is good to go.

**Comment by michaeldfallen** [comment]
Readme looks good enough for now -> merging :shipit:

**Comment by n10v** [comment]
Supeer

**Comment by michaeldfallen** [comment]
Just released it on brew: https://github.com/michaeldfallen/git-radar/releases/tag/v0.4

**Pull request merged**
